# general settings
task: SportClassification
gpu_ids: [0]
seed: 42

datasets:
  train: 
    name: train_dataset
    type: sport
    csv_path: /home/viliar/Documents/VKMADE/contest/data/val_part_clean_1.csv
    dataroot: /home/viliar/Documents/VKMADE/contest/data/train

    size: 224

    dataloader_shuffle: true
    dataloader_batch_size: 176
    dataloader_num_workers: 8

    # from SwinTransformer ImageNet config
    augs:
      input_size: 224
      color_jitter: 0.4
      auto_augment: rand-m9-mstd0.5-inc1
      reprob: 0.25
      remode: pixel
      recount: 1

    mixup:
      mixup_alpha: 0.8
      cutmix_alpha: 1.0
      prob: 1.0
      switch_prob: 0.5
      mode: batch
      num_classes: 30

  val:
    name: val_dataset
    type: sport
    csv_path: /home/viliar/Documents/VKMADE/contest/data/val_part_clean_1.csv
    dataroot: /home/viliar/Documents/VKMADE/contest/data/train

    size: 224

    dataloader_shuffle: false
    dataloader_batch_size: 192
    dataloader_num_workers: 8

    augs:
      input_size: 224

net:
  net_type: nextvit
  stem_chs: [64, 32, 64]
  depths: [3, 4, 30, 3]
  path_dropout: 0.2
  size: 224
  num_classes: 30

train:
  loss: cross_entropy
  weight: [0.81401148, 1.54015614, 1.0865182 , 1.32669591, 0.60041022,
       0.86276859, 0.8397742 , 1.06434436, 0.70345736, 1.08573821,
       1.16520288, 1.06885748, 1.00227524, 0.70313033, 0.96456207,
       1.8648993 , 1.44453996, 0.76890358, 0.75963502, 1.28063788,
       1.19654536, 0.77283257, 1.13290886, 1.0650939 , 1.17882567,
       1.36255255, 0.8717195 , 1.24377741, 0.81488865, 1.77933333]

  weight_decay: !!float 1e-8
  lr: !!float 5e-6

  scheduler_type: MultiStepLR
  scheduler_milestones: [10, 20, 30, 50, 80, 120]
  scheduler_gamma: 0.5
  optimizer_reuse: true

  param_strict: true

  checkpoint_test: 1
  checkpoint_save: 30

  exp_dir: large_image_net_augs_mixup_clean_all
